### ISSUE TITLE
sysrepo /bin/sh: 1: PROTOBUFC_PROTOC_EXECUTABLE-NOTFOUND: not found

### ISSUE THREAD

**Issue by taeasy** [openwrt-management/packages#16]
make[2]: Entering directory `/home/main/x86/feeds/management/sysrepo'
CFLAGS="-Os -pipe -march=pentium4 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/sysrepo-0b12938bf5d4bcf6d6ebeb126a2b1f489fa078a7:sysrepo-0b12938bf5d4bcf6d6ebeb126a2b1f489fa078a7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include/fortify -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include " CXXFLAGS="-Os -pipe -march=pentium4 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/sysrepo-0b12938bf5d4bcf6d6ebeb126a2b1f489fa078a7:sysrepo-0b12938bf5d4bcf6d6ebeb126a2b1f489fa078a7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/usr/include -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include/fortify -I/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/include " LDFLAGS="-L/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/usr/lib -L/home/main/x86/staging_dir/target-i386_pentium4_musl-1.1.15/lib -L/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/usr/lib -L/home/main/x86/staging_dir/toolchain-i386_pentium4_gcc-5.3.0_musl-1.1.15/lib -znow -zrelro " make   -C /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/sysrepo-0b12938bf5d4bcf6d6ebeb126a2b1f489fa078a7/. AR="i486-openwrt-linux-musl-gcc-ar" AS="i486-openwrt-linux-musl-gcc -c -Os -pipe -march=pentium4 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/sysrepo-0b12938bf5d4bcf6d6ebeb126a2b1f489fa078a7:sysrepo-0b12938bf5d4bcf6d6ebeb126a2b1f489fa078a7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=i486-openwrt-linux-musl-ld NM="i486-openwrt-linux-musl-gcc-nm" CC="i486-openwrt-linux-musl-gcc" GCC="i486-openwrt-linux-musl-gcc" CXX="i486-openwrt-linux-musl-g++" RANLIB="i486-openwrt-linux-musl-gcc-ranlib" STRIP=i486-openwrt-linux-musl-strip OBJCOPY=i486-openwrt-linux-musl-objcopy OBJDUMP=i486-openwrt-linux-musl-objdump SIZE=i486-openwrt-linux-musl-size CROSS="i486-openwrt-linux-musl-" ARCH="i386" ;
make[3]: Entering directory `/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/sysrepo-0b12938bf5d4bcf6d6ebeb126a2b1f489fa078a7'
make[4]: Entering directory `/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/sysrepo-0b12938bf5d4bcf6d6ebeb126a2b1f489fa078a7'
make[5]: Entering directory `/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/sysrepo-0b12938bf5d4bcf6d6ebeb126a2b1f489fa078a7'
[  1%] Running C protocol buffer compiler on /home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/sysrepo-0b12938bf5d4bcf6d6ebeb126a2b1f489fa078a7/src/sysrepo.proto
/bin/sh: 1: PROTOBUFC_PROTOC_EXECUTABLE-NOTFOUND: not found
make[5]: *** [src/common/sysrepo.pb-c.c] Error 127
make[5]: Leaving directory `/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/sysrepo-0b12938bf5d4bcf6d6ebeb126a2b1f489fa078a7'
make[4]: *** [src/CMakeFiles/sysrepo-engine.dir/all] Error 2
make[4]: Leaving directory `/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/sysrepo-0b12938bf5d4bcf6d6ebeb126a2b1f489fa078a7'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/sysrepo-0b12938bf5d4bcf6d6ebeb126a2b1f489fa078a7'
make[2]: *** [/home/main/x86/build_dir/target-i386_pentium4_musl-1.1.15/sysrepo-0b12938bf5d4bcf6d6ebeb126a2b1f489fa078a7/.built] Error 2
make[2]: Leaving directory `/home/main/x86/feeds/management/sysrepo'
make[1]: *** [package/feeds/management/sysrepo/compile] Error 2
make[1]: Leaving directory `/home/main/x86'
make: *** [package/sysrepo/compile] Error 2
main@debian:~/x86$

**Comment by lperkov** [comment]
This is now fixed in the latest version.
