### ISSUE TITLE
libssh compile error

### ISSUE THREAD

**Issue by taeasy** [openwrt-management/packages#5]
make[3]: Leaving directory `/home/main/x86/feeds/management/libnetconf'
make[3]: Entering directory `/home/main/x86/feeds/management/libssh'
CFLAGS="-Os -pipe -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/main/x86/staging_dir/target-x86_64_musl-1.1.10/usr/include -I/home/main/x86/staging_dir/target-x86_64_musl-1.1.10/include -I/home/main/x86/staging_dir/toolchain-x86_64_gcc-4.8-linaro_musl-1.1.10/usr/include -I/home/main/x86/staging_dir/toolchain-x86_64_gcc-4.8-linaro_musl-1.1.10/include/fortify -I/home/main/x86/staging_dir/toolchain-x86_64_gcc-4.8-linaro_musl-1.1.10/include " CXXFLAGS="-Os -pipe -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/main/x86/staging_dir/target-x86_64_musl-1.1.10/usr/include -I/home/main/x86/staging_dir/target-x86_64_musl-1.1.10/include -I/home/main/x86/staging_dir/toolchain-x86_64_gcc-4.8-linaro_musl-1.1.10/usr/include -I/home/main/x86/staging_dir/toolchain-x86_64_gcc-4.8-linaro_musl-1.1.10/include/fortify -I/home/main/x86/staging_dir/toolchain-x86_64_gcc-4.8-linaro_musl-1.1.10/include " LDFLAGS="-L/home/main/x86/staging_dir/target-x86_64_musl-1.1.10/usr/lib -L/home/main/x86/staging_dir/target-x86_64_musl-1.1.10/lib -L/home/main/x86/staging_dir/toolchain-x86_64_gcc-4.8-linaro_musl-1.1.10/usr/lib -L/home/main/x86/staging_dir/toolchain-x86_64_gcc-4.8-linaro_musl-1.1.10/lib -znow -zrelro " make   -C /home/main/x86/build_dir/target-x86_64_musl-1.1.10/libssh-2014-07-10/. AR="x86_64-openwrt-linux-musl-gcc-ar" AS="x86_64-openwrt-linux-musl-gcc -c -Os -pipe -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=x86_64-openwrt-linux-musl-ld NM="x86_64-openwrt-linux-musl-gcc-nm" CC="x86_64-openwrt-linux-musl-gcc" GCC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" RANLIB="x86_64-openwrt-linux-musl-gcc-ranlib" STRIP=x86_64-openwrt-linux-musl-strip OBJCOPY=x86_64-openwrt-linux-musl-objcopy OBJDUMP=x86_64-openwrt-linux-musl-objdump SIZE=x86_64-openwrt-linux-musl-size CROSS="x86_64-openwrt-linux-musl-" ARCH="x86_64" ;
make[4]: Entering directory `/home/main/x86/build_dir/target-x86_64_musl-1.1.10/libssh-2014-07-10'
make[5]: Entering directory `/home/main/x86/build_dir/target-x86_64_musl-1.1.10/libssh-2014-07-10'
make[6]: Entering directory `/home/main/x86/build_dir/target-x86_64_musl-1.1.10/libssh-2014-07-10'
make[6]: Leaving directory `/home/main/x86/build_dir/target-x86_64_musl-1.1.10/libssh-2014-07-10'
make[6]: Entering directory `/home/main/x86/build_dir/target-x86_64_musl-1.1.10/libssh-2014-07-10'
[  2%] Building C object src/CMakeFiles/ssh_shared.dir/agent.c.o
In file included from /home/main/x86/build_dir/target-x86_64_musl-1.1.10/libssh-2014-07-10/include/libssh/agent.h:24:0,
                 from /home/main/x86/build_dir/target-x86_64_musl-1.1.10/libssh-2014-07-10/src/agent.c:52:
/home/main/x86/build_dir/target-x86_64_musl-1.1.10/libssh-2014-07-10/include/libssh/libssh.h:488:49: error: unknown type name 'mode_t'
 LIBSSH_API int ssh_mkdir (const char *pathname, mode_t mode);
                                                 ^
make[6]: *** [src/CMakeFiles/ssh_shared.dir/agent.c.o] Error 1
make[6]: Leaving directory `/home/main/x86/build_dir/target-x86_64_musl-1.1.10/libssh-2014-07-10'
make[5]: *** [src/CMakeFiles/ssh_shared.dir/all] Error 2
make[5]: Leaving directory `/home/main/x86/build_dir/target-x86_64_musl-1.1.10/libssh-2014-07-10'
make[4]: *** [all] Error 2
make[4]: Leaving directory `/home/main/x86/build_dir/target-x86_64_musl-1.1.10/libssh-2014-07-10'
make[3]: *** [/home/main/x86/build_dir/target-x86_64_musl-1.1.10/libssh-2014-07-10/.built] Error 2
make[3]: Leaving directory `/home/main/x86/feeds/management/libssh'
make[2]: *** [package/feeds/management/libssh/compile] Error 2
make[2]: Leaving directory `/home/main/x86'
make[1]: *** [/home/main/x86/staging_dir/target-x86_64_musl-1.1.10/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/main/x86'
make: *** [world] Error 2
main@bogon:~/x86$

**Comment by plntyk** [comment]
```
libssh: fix musl headers

Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>
---
 libssh/patches/002-musl_mode_t.patch | 10 ++++++++++
 1 file changed, 10 insertions(+)
 create mode 100644 libssh/patches/002-musl_mode_t.patch

diff --git a/libssh/patches/002-musl_mode_t.patch b/libssh/patches/002-musl_mode_t.patch
new file mode 100644
index 0000000..a5975ac
--- /dev/null
+++ b/libssh/patches/002-musl_mode_t.patch
@@ -0,0 +1,10 @@
+--- a/include/libssh/libssh.h
++++ b/include/libssh/libssh.h
+@@ -58,6 +58,7 @@
+ #else /* _MSC_VER */
+   #include <unistd.h>
+   #include <inttypes.h>
++  #include <sys/types.h>
+ #endif /* _MSC_VER */
+ 
+ #ifdef _WIN32
-- 
2.5.1

```

**Comment by BrettTrotter** [comment]
Upstream has resolved the issue and is in the repo.

**Comment by lperkov** [comment]
Please send a pull request.
