### ISSUE TITLE
libyang compile error

### ISSUE THREAD

**Issue by taeasy** [openwrt-management/packages#7]
rm -f /home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4/.configured_*
touch /home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4/.configured_yyyyyyyy
CFLAGS="-Os -pipe -march=i486 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable  -I/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/include -I/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/include -I/home/main/x86/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/main/x86/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/include " CXXFLAGS="-Os -pipe -march=i486 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable  -I/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/include -I/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/include -I/home/main/x86/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/main/x86/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/include " LDFLAGS="-L/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/lib -L/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/lib -L/home/main/x86/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/main/x86/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/lib " make   -C /home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4/. AR="i486-openwrt-linux-uclibc-gcc-ar" AS="i486-openwrt-linux-uclibc-gcc -c -Os -pipe -march=i486 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable" LD=i486-openwrt-linux-uclibc-ld NM="i486-openwrt-linux-uclibc-gcc-nm" CC="i486-openwrt-linux-uclibc-gcc" GCC="i486-openwrt-linux-uclibc-gcc" CXX="i486-openwrt-linux-uclibc-g++" RANLIB="i486-openwrt-linux-uclibc-gcc-ranlib" STRIP=i486-openwrt-linux-uclibc-strip OBJCOPY=i486-openwrt-linux-uclibc-objcopy OBJDUMP=i486-openwrt-linux-uclibc-objdump SIZE=i486-openwrt-linux-uclibc-size CROSS="i486-openwrt-linux-uclibc-" ARCH="i386" ;
make[4]: Entering directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4'
make[5]: Entering directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4'
make[6]: Entering directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4'
Scanning dependencies of target yang
make[6]: Leaving directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4'
make[6]: Entering directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4'
[  4%] Building C object CMakeFiles/yang.dir/src/common.c.o
/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4/src/common.c: In function 'transform_xml2json':
/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4/src/common.c:238:9: warning: implicit declaration of function 'strndup' [-Wimplicit-function-declaration]
         prefix = strndup(id, id_len);
         ^
/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4/src/common.c:238:18: warning: incompatible implicit declaration of built-in function 'strndup' [enabled by default]
         prefix = strndup(id, id_len);
                  ^
/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4/src/common.c: In function 'transform_json2xml':
/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4/src/common.c:169:42: warning: 'pref' may be used uninitialized in this function [-Wmaybe-uninitialized]
                 (*prefixes)[*ns_count-1] = (char *)pref;
                                          ^
[  8%] Building C object CMakeFiles/yang.dir/src/context.c.o
[ 12%] Building C object CMakeFiles/yang.dir/src/log.c.o
In file included from /home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4/src/libyang.h:29:0,
                 from /home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4/src/common.h:28,
                 from /home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4/src/log.c:27:
/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4/src/xml.h:219:20: error: unknown type name 'ssize_t'
 int lyxml_dump_clb(ssize_t (*writeclb)(void *arg, const void *buf, size_t count), void *arg, struct lyxml_elem *elem, int options);
                    ^
In file included from /home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4/src/common.h:28:0,
                 from /home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4/src/log.c:27:
/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4/src/libyang.h:529:19: error: unknown type name 'ssize_t'
 int lys_print_clb(ssize_t (*writeclb)(void *arg, const void *buf, size_t count), void *arg, struct lys_module *module, LYS_OUTFORMAT format, const char *target_node);
                   ^
/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4/src/libyang.h:584:19: error: unknown type name 'ssize_t'
 int lyd_print_clb(ssize_t (*writeclb)(void *arg, const void *buf, size_t count), void *arg, struct lyd_node *root, LYD_FORMAT format);
                   ^
make[6]: *** [CMakeFiles/yang.dir/src/log.c.o] Error 1
make[6]: Leaving directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4'
make[5]: *** [CMakeFiles/yang.dir/all] Error 2
make[5]: Leaving directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4'
make[4]: *** [all] Error 2
make[4]: Leaving directory `/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4'
make[3]: *** [/home/main/x86/build_dir/target-i386_i486_uClibc-0.9.33.2/libyang-0.3.4/.built] Error 2
make[3]: Leaving directory `/home/main/x86/feeds/management/libyang'
make[2]: *** [package/feeds/management/libyang/compile] Error 2
make[2]: Leaving directory `/home/main/x86'
make[1]: *** [/home/main/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/main/x86'

**Comment by taeasy** [comment]
[ 62%] Building C object CMakeFiles/yang.dir/src/printer_yang.c.o
[ 66%] Building C object CMakeFiles/yang.dir/src/printer_xml.c.o
/home/main/x86/build_dir/target-x86_64_uClibc-0.9.33.2/libyang-0.3.4/src/printer_xml.c: In function 'xml_print_anyxml':
/home/main/x86/build_dir/target-x86_64_uClibc-0.9.33.2/libyang-0.3.4/src/printer_xml.c:213:9: warning: implicit declaration of function 'open_memstream' [-Wimplicit-function-declaration]
         stream = open_memstream(&buf, &buf_size);
         ^
/home/main/x86/build_dir/target-x86_64_uClibc-0.9.33.2/libyang-0.3.4/src/printer_xml.c:213:16: warning: assignment makes pointer from integer without a cast [enabled by default]
         stream = open_memstream(&buf, &buf_size);
                ^
[ 70%] Building C object CMakeFiles/yang.dir/src/printer_tree.c.o
[ 75%] Building C object CMakeFiles/yang.dir/src/printer_info.c.o
[ 79%] Building C object CMakeFiles/yang.dir/src/printer_json.c.o
[ 83%] Building C object CMakeFiles/yang.dir/src/yang_types.c.o
Linking C shared library libyang.so
make[6]: Leaving directory `/home/main/x86/build_dir/target-x86_64_uClibc-0.9.33.2/libyang-0.3.4'
[ 83%] Built target yang
make[6]: Entering directory `/home/main/x86/build_dir/target-x86_64_uClibc-0.9.33.2/libyang-0.3.4'
Scanning dependencies of target yanglint
make[6]: Leaving directory `/home/main/x86/build_dir/target-x86_64_uClibc-0.9.33.2/libyang-0.3.4'
make[6]: Entering directory `/home/main/x86/build_dir/target-x86_64_uClibc-0.9.33.2/libyang-0.3.4'
[ 87%] Building C object CMakeFiles/yanglint.dir/tools/lint/main.c.o
[ 91%] Building C object CMakeFiles/yanglint.dir/tools/lint/commands.c.o
[ 95%] Building C object CMakeFiles/yanglint.dir/tools/lint/completion.c.o
[100%] Building C object CMakeFiles/yanglint.dir/linenoise/linenoise.c.o
Linking C executable yanglint
libyang.so.0.3.4: undefined reference to `__isnanl'
libyang.so.0.3.4: undefined reference to `__signbitl'
libyang.so.0.3.4: undefined reference to `__isinfl'
libyang.so.0.3.4: undefined reference to `__finitel'
collect2: error: ld returned 1 exit status
make[6]: *** [yanglint] Error 1
make[6]: Leaving directory `/home/main/x86/build_dir/target-x86_64_uClibc-0.9.33.2/libyang-0.3.4'
make[5]: *** [CMakeFiles/yanglint.dir/all] Error 2
make[5]: Leaving directory `/home/main/x86/build_dir/target-x86_64_uClibc-0.9.33.2/libyang-0.3.4'
make[4]: *** [all] Error 2
make[4]: Leaving directory `/home/main/x86/build_dir/target-x86_64_uClibc-0.9.33.2/libyang-0.3.4'
make[3]: *** [/home/main/x86/build_dir/target-x86_64_uClibc-0.9.33.2/libyang-0.3.4/.built] Error 2
make[3]: Leaving directory `/home/main/x86/feeds/management/libyang'
make[2]: *** [package/feeds/management/libyang/compile] Error 2
make[2]: Leaving directory `/home/main/x86'
make[1]: *** [/home/main/x86/staging_dir/target-x86_64_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/main/x86'

**Comment by lperkov** [comment]
libyang has been updated. closing.
